import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Leaf, Sparkles, Flower2, Heart, Star, Plus, Minus, Menu, X, MapPin, Clock, ChevronDown, Hand, Sun } from 'lucide-react';
import Booking from '../components/booking';

const categories = [
  { name: 'Trattamenti viso', subtitle: 'La tua pelle, nella sua luce migliore', icon: Sparkles, services: [{ name: 'Pulizia viso profonda', description: 'Detersione, esfoliazione e maschera su misura', duration: '60 min', price: 55 }, { name: 'Rituale viso idratante', description: 'Un abbraccio di idratazione per la tua pelle', duration: '60 min', price: 65 }, { name: 'Trattamento illuminante', description: 'Vitamina C e luminosità naturale', duration: '50 min', price: 70 }, { name: 'Lifting naturale Gua Sha', description: 'Manualità delicate, bellezza ritrovata', duration: '45 min', price: 60 }] },
  { name: 'Trattamenti corpo', subtitle: 'Ritrova leggerezza ed equilibrio', icon: Flower2, services: [{ name: 'Scrub corpo rigenerante', description: 'Esfoliazione delicata e nutrimento', duration: '45 min', price: 50 }, { name: 'Rituale corpo drenante', description: 'Manualità mirate per sentirti più leggera', duration: '60 min', price: 75 }, { name: 'Avvolgimento nutriente', description: 'Un rituale di morbidezza per tutto il corpo', duration: '60 min', price: 65 }] },
  { name: 'Massaggi & benessere', subtitle: 'Lascia andare. Respira. Rilassati.', icon: Leaf, services: [{ name: 'Massaggio rilassante', description: 'Un momento di calma con oli profumati', duration: '60 min', price: 65 }, { name: 'Massaggio decontratturante', description: 'Per sciogliere le tensioni quotidiane', duration: '50 min', price: 70 }, { name: 'Rituale hot stone', description: 'Il calore delle pietre e la quiete', duration: '75 min', price: 85 }] },
  { name: 'Mani & piedi', subtitle: 'La bellezza nei piccoli dettagli', icon: Hand, services: [{ name: 'Manicure con smalto', description: 'Cura completa e colore a tua scelta', duration: '40 min', price: 25 }, { name: 'Manicure semipermanente', description: 'Colore brillante, a lungo', duration: '60 min', price: 35 }, { name: 'Pedicure estetico', description: 'Benessere e cura dei piedi', duration: '50 min', price: 40 }] },
  { name: 'Epilazione', subtitle: 'Una pelle liscia, una nuova leggerezza', icon: Sun, services: [{ name: 'Epilazione gambe complete', description: 'Cera delicata per una pelle morbida', duration: '40 min', price: 35 }, { name: 'Epilazione inguine', description: 'Trattamento delicato e personalizzato', duration: '20 min', price: 20 }, { name: 'Design sopracciglia', description: 'Una forma che valorizza il tuo viso', duration: '20 min', price: 15 }] },
];
function Brand({ light = false }: { light?: boolean }) { return <a href="#inizio" className={`brand ${light ? 'light' : ''}`} aria-label="Lumé, torna all'inizio"><Flower2 strokeWidth={1} size={35} /><span>lumé<small>BEAUTY & WELLNESS</small></span></a>; }
function Stars() { return <div className="stars" aria-label="5 stelle su 5">{Array.from({ length: 5 }, (_, i) => <Star key={i} size={13} fill="currentColor" strokeWidth={1} />)}</div>; }
export default function Home() {
  const [open, setOpen] = useState<number | null>(0);
  const [menu, setMenu] = useState(false);
  const [service, setService] = useState('');
  const book = (name: string) => { setService(name); document.getElementById('prenota')?.scrollIntoView({ behavior: 'smooth' }); };
  return <>
    <a className="skip-link" href="#trattamenti">Vai al contenuto</a>
    <header className="site-header"><div className="header-inner"><Brand /><nav className={menu ? 'nav open' : 'nav'} aria-label="Navigazione principale">{[['La nostra filosofia', '#filosofia'], ['Trattamenti & prezzi', '#trattamenti'], ['Dicono di noi', '#recensioni'], ['Contatti', '#contatti']].map(([text, href]) => <a key={href} href={href} onClick={() => setMenu(false)}>{text}</a>)}</nav><a className="button header-book" href="#prenota">Prenota un momento <ArrowUpRight size={16} /></a><button className="mobile-menu" aria-label={menu ? 'Chiudi menu' : 'Apri menu'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div></header>
    <main>
      <section className="hero" id="inizio"><div className="hero-copy"><span className="eyebrow"><span className="tiny-line" /> IL BENESSERE INIZIA DA TE</span><h1>Rallenta.<br />Ritrova il tuo<br /><em>splendore.</em></h1><p>Uno spazio di quiete, una cura autentica.<br className="desktop-break" /> Rituali di bellezza pensati per farti stare bene,<br className="desktop-break" /> dentro e fuori.</p><div className="hero-actions"><a className="button primary" href="#prenota">Prenota il tuo momento <ArrowUpRight size={18} /></a><a className="text-link" href="#trattamenti">Esplora i trattamenti <ArrowRight size={16} /></a></div><div className="hero-proof"><div className="proof-symbol"><Heart size={19} strokeWidth={1.4} /></div><div><Stars /><span>Piccoli rituali. Grandi sensazioni.</span></div></div></div><div className="hero-photo"><img src="/images/hero.webp" alt="Massaggio viso delicato in un ambiente luminoso e rilassante" fetchPriority="high" /><div className="photo-shade" /><div className="photo-caption"><span>IL LUSSO DI PRENDERSI CURA DI SÉ</span><p>Il tuo momento, <em>la tua luce.</em></p></div><div className="round-seal"><Flower2 size={30} strokeWidth={1} /><span>BELLEZZA<br />IN EQUILIBRIO</span></div></div><a className="scroll-hint" href="#filosofia"><span>CONCEDITI UNA PAUSA</span><ChevronDown size={14} /></a></section>
      <div className="values-strip"><span><Leaf /> Ingredienti selezionati</span><span><Heart /> Cura personalizzata</span><span><Flower2 /> Armonia, dentro e fuori</span><span><Sparkles /> La tua bellezza naturale</span></div>
      <section className="philosophy section" id="filosofia"><span className="eyebrow">BENVENUTA DA LUMÉ</span><h2>Non solo bellezza.<br />Un modo di <em>sentirsi bene.</em></h2><div className="philosophy-text"><p>Crediamo in una bellezza che non ha fretta. Quella che nasce dall’ascolto, dai gesti gentili e dal tempo che scegli di dedicarti.</p><p>Da Lumé, ogni trattamento è un piccolo rituale su misura. Un incontro tra professionalità e sensibilità, per valorizzare ciò che ti rende unica.</p><span className="signature">Con cura, il team Lumé</span></div></section>
      <section className="services section" id="trattamenti"><div className="service-intro"><span className="eyebrow">IL NOSTRO MENU DI BELLEZZA</span><h2>Una cura per<br />ogni <em>esigenza.</em></h2><p>Scegli il tuo rituale. Scopri trattamenti,<br className="desktop-break" /> tempi e prezzi, con tutta la semplicità<br className="desktop-break" /> che meriti.</p><div className="ritual-image"><img src="/images/ritual.webp" alt="Trattamento viso con pietra Gua Sha" loading="lazy" /><span>Gesti gentili, risultati che senti.</span></div><p className="service-note"><Leaf size={15} /> Non sai da dove iniziare? <a href="#prenota" onClick={() => setService('Consulenza personalizzata')}>Parliamone insieme.</a></p></div><div className="accordion">{categories.map((cat, i) => <div key={cat.name} className={`category ${open === i ? 'expanded' : ''}`}><h3><button className="category-trigger" aria-expanded={open === i} aria-controls={`category-${i}`} onClick={() => setOpen(open === i ? null : i)}><span className="category-icon"><cat.icon size={24} strokeWidth={1.2} /></span><span className="category-text"><span>{cat.name}</span><small>{cat.subtitle}</small></span><span className="toggle-icon">{open === i ? <Minus size={19} /> : <Plus size={19} />}</span></button></h3><div className="category-content" id={`category-${i}`} inert={open !== i}><div className="category-content-inner">{cat.services.map(item => <button className="service-item" key={item.name} onClick={() => book(item.name)} aria-label={`Richiedi ${item.name}, ${item.price} euro`}><span className="service-info"><span className="service-name">{item.name}</span><span className="service-desc">{item.description}</span><span className="duration"><Clock size={11} />{item.duration}</span></span><span className="price-leader" /><span className="service-price">€ {item.price}<ArrowUpRight size={14} /></span></button>)}<p className="category-tip">Un primo incontro per ascoltare la tua pelle, sempre incluso.</p></div></div></div>)}<p className="price-note">Listino dimostrativo · Prezzi IVA inclusa. Seleziona un servizio per provarne la prenotazione.</p></div></section>
      <section className="reviews-section" id="recensioni"><div className="section"><div className="reviews-heading"><div><span className="eyebrow">PAROLE CHE CI FANNO BENE</span><h2>La bellezza delle <em>vostre parole.</em></h2></div><span className="review-demo">Recensioni illustrative</span></div><div className="review-grid">{[{ text: 'Un’oasi di pace nel cuore della città. Il trattamento viso è stato meraviglioso e la mia pelle non è mai stata così luminosa. Tornerò sicuramente.', name: 'Giulia M.', service: 'Trattamento viso' }, { text: 'Qui non ci si sente una cliente, ma una persona di cui prendersi cura. Il massaggio mi ha rimessa al mondo. Un’ora tutta per me, finalmente.', name: 'Francesca R.', service: 'Massaggio rilassante' }, { text: 'Ambiente curato, mani esperte e un’accoglienza speciale. Adoro l’attenzione ai piccoli dettagli. Lumé è diventato il mio appuntamento preferito.', name: 'Alessandra P.', service: 'Rituale di bellezza' }].map(r => <article className="review-card" key={r.name}><Stars /><blockquote>“{r.text}”</blockquote><div className="review-author"><span className="avatar">{r.name.charAt(0)}</span><span><strong>{r.name}</strong><small>{r.service}</small></span><Heart size={17} strokeWidth={1.2} /></div></article>)}</div></div></section>
      <Booking service={service} />
      <section className="contact-strip" id="contatti"><div className="contact-inner"><div><MapPin strokeWidth={1.3} /><span><strong>Vieni a trovarci</strong><small>Via della Luce 12, Milano · Indirizzo demo</small></span></div><a href="https://www.google.com/maps/search/?api=1&query=Milano%2C%20Italia" target="_blank" rel="noopener noreferrer">Esplora Milano su Maps <ArrowUpRight size={16} /></a><div><Clock strokeWidth={1.3} /><span><strong>Il tempo per te</strong><small>Lun – Sab: 09:00 – 19:00 · Orari demo</small></span></div></div></section>
    </main>
    <footer><div className="footer-main"><Brand light /><p>La tua bellezza, senza fretta.<br />Il tuo benessere, con amore.</p><a className="footer-top" href="#inizio">Torna su <ArrowUpRight size={18} /></a></div><div className="footer-bottom"><span>© 2026 Lumé — Beauty & Wellness</span><span>Progetto dimostrativo · Centro, listino e recensioni fittizi</span><span>Fotografie: Pexels</span></div></footer>
  </>;
}